INSERT INTO biome (biome_reference,biome_name) Values ('DUNLL','dungeon (low level)'
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('dire rats',0.3,'animal','urban','temperate','NN','swarm')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('fire beetles',0.3,'underground','temperate',''NN','swarm')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('skeletons',0.3,'undead','ruins','temperate','NE','swarm')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('giant centipede',0.5,'vermin','underground','temperate','NN','swarm')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('spider swarm',1,'vermin','forest/jungle','temperate','NN','swarm')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('zombie',0.5,'undead','ruins','temperate','NE','tank')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('choker',2,'aberration','underground','temperate','CE','assassin')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('skeleton champion',2,'undead','ruins','temperate','NE','leader')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('goblins',0.3,'humanoid','forest/jungle','temperate','NE','swarm')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('ghoul',1,'undead','ruins','temperate','CE','damage')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('giant spiders',1,'vermin','forest/jungle','temperate','NN','none')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('cockatrice',3,'magical beast','plain','temperate','NN','special')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('gelatinous cube',3,'ooze','ruins','temperate','NN','special')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('rust monster',3,'aberration','underground',temperate','NN','special')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('shadow',3,'undead','ruins','temperate','CE','assassin')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('wight',3,'undead','ruins','temperate','LE','none')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('stirge',0.5,'magical beast','swamp','tropical','NN','ambush')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('darkmantle',1,'magical beast','underground','temperate','NN','assassin')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('troglodyte',1,'humanoid','underground','temperate','CE','swarm')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('bugbear',2,'humanoid','hill','temperate','CE','assassin')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('vargouille',2,'outsider','ruins','temperate','NE','special')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('gray ooze',4,'ooze','swamp','cold','NN','none')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('mimic',4,'aberration','underground','temperate','NN','none')
INSERT INTO creature (creature_name, challenge_rating,type,environment,climate,alignment,combat_role) VALUES ('ogre',3,'humanoid','hill','temperate','CE','tank')


INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('dire rats','DUNLL','1d6',6,1)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('fire beetles','DUNLL',12,7)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('skeletons','DUNLL','1d6',20,13)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('giant centipede','1d4',24,21)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('spider swarm','1',26,25)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('zombie','DUNLL','1d6',32,27)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('choker','DUNLL','1',34,33)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('skeleton champion','1',36,35)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('goblins','DUNLL','2d6',44,37)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('ghoul','DUNLL','1d4',48,45)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('giant spiders','DUNLL','1d4',54,49)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('cockatrice','DUNLL','1',56,55)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('gelatinous cube','DUNLL','1',60,57)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('rust monster','DUNLL','1',64,61)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('shadow','DUNLL','1',68,65)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('wight','DUNLL','1',70,69)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('stirge','DUNLL','2d4',76,71)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('darkmantle','DUNLL','1d6',82,77)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('troglodyte','DUNLL','1d6',86,83)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('bugbear','DUNLL','1d4',90,87)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('vargouille','DUNLL','1d4',92,91)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('gray ooze','DUNLL','1',94,93)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('mimic','DUNLL','1',96,95)
INSERT INTO monster_biome (monster_key, biome_key, number, max_chance, min_chance) VALUES ('ogre','DUNLL','1',100,97)
