INSERT INTO Biome (biomeReference,biomeName) VALUES ('DUNLL','dungeon (low level)');

INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('dire rats','0.3','animal','urban','temperate','NN','swarm');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('fire beetles','0.3', 'vermin', 'underground','temperate','NN','swarm');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('skeletons','0.3','undead','ruins','temperate','NE','swarm');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('giant centipede','0.5','vermin','underground','temperate','NN','swarm');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('spider swarm','1','vermin','forest/jungle','temperate','NN','swarm');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('zombie','0.5','undead','ruins','temperate','NE','tank');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('choker','2','aberration','underground','temperate','CE','assassin');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('skeleton champion','2','undead','ruins','temperate','NE','leader');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('goblins','0.3','humanoid','forest/jungle','temperate','NE','swarm');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('ghoul','1','undead','ruins','temperate','CE','damage');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('giant spiders','1','vermin','forest/jungle','temperate','NN','none');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('cockatrice','3','magical beast','plain','temperate','NN','special');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('gelatinous cube','3','ooze','ruins','temperate','NN','special');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('rust monster','3','aberration','underground','temperate','NN','special');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('shadow','3','undead','ruins','temperate','CE','assassin');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('wight','3','undead','ruins','temperate','LE','none');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('stirge','0.5','magical beast','swamp','tropical','NN','ambush');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('darkmantle','1','magical beast','underground','temperate','NN','assassin');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('troglodyte','1','humanoid','underground','temperate','CE','swarm');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('bugbear','2','humanoid','hill','temperate','CE','assassin');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('vargouille','2','outsider','ruins','temperate','NE','special');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('gray ooze','4','ooze','swamp','cold','NN','none');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('mimic','4','aberration','underground','temperate','NN','none');
INSERT INTO Creature (creatureName, challengeRating,type,environment,climate,alignment,combatRole) VALUES ('ogre','3','humanoid','hill','temperate','CE','tank');

INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('dire rats','DUNLL','1d6',6,1);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('fire beetles','DUNLL','1d6',12,7);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('skeletons','DUNLL','1d6',20,13);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('giant centipede','DUNLL','1d4',24,21);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('spider swarm','DUNLL','1',26,25);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('zombie','DUNLL','1d6',32,27);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('choker','DUNLL','1',34,33);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('skeleton champion','DUNLL','1',36,35);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('goblins','DUNLL','2d6',44,37);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('ghoul','DUNLL','1d4',48,45);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('giant spiders','DUNLL','1d4',54,49);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('cockatrice','DUNLL','1',56,55);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('gelatinous cube','DUNLL','1',60,57);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('rust monster','DUNLL','1',64,61);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('shadow','DUNLL','1',68,65);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('wight','DUNLL','1',70,69);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('stirge','DUNLL','2d4',76,71);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('darkmantle','DUNLL','1d6',82,77);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('troglodyte','DUNLL','1d6',86,83);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('bugbear','DUNLL','1d4',90,87);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('vargouille','DUNLL','1d4',92,91);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('gray ooze','DUNLL','1',94,93);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('mimic','DUNLL','1',96,95);
INSERT INTO EncounterChart (monsterKey, biomeKey, number, maxChance, minChance) VALUES ('ogre','DUNLL','1',100,97);